### ISSUE TITLE
How to calculate the execution time of an async function in JavaScript?

### ISSUE THREAD

**Issue by 137591** [ehmicky/ehmicky#1]
I'm sorry to bother you here. I've been following the question you asked on Stack Overflow in 2017[:](https://stackoverflow.com/questions/45752454/how-to-calculate-the-execution-time-of-an-async-function-in-javascript) "How to calculate the execution time of an async function in JavaScript?" If you add timestamps before and after an asynchronous function, the measured time will definitely be inaccurate because it includes the execution time of other tasks in the microtask queue. May I ask if this issue has been resolved? I'm working in a browser environment rather than a Node.js environment. I would be extremely grateful if you could provide an answer. Thank you!

**Comment by ehmicky** [comment]
Hi,

Unfortunately, there's no way around that.

Let's say that the asynchronous logic is reading a file. A syscall is made to do that, and the OS is sending a "done" event back to Node.js once the file has been read. When Node.js receives that "done" event, it queues it. Otherwise, it would need to interrupt whatever code is currently running, which it would obviously never do. Therefore, by the time the "done" event is processed, other unrelated logic has been running.

So, there's no way to measure async tasks completely accurately with the Node.js event loop. The best you can do is to try to minimize the other async tasks currently ongoing, for benchmarking purpose.
